//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.02 at 01:53:27 PM MESZ 
//

package org.universAAL.ucc.configuration.model.configurationdefinition;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * de.cas.merlin.aal.configuration.model.configurationdefinition package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Configuration_QNAME = new QName("http://universaal.cas.de", "configuration");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * de.cas.merlin.aal.configuration.model.configurationdefinition
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link ConfigItem }
	 * 
	 */
	public ConfigItem createConfigItem() {
		return new ConfigItem();
	}

	/**
	 * Create an instance of {@link Validators }
	 * 
	 */
	public Validators createValidators() {
		return new Validators();
	}

	/**
	 * Create an instance of {@link Validator }
	 * 
	 */
	public Validator createValidator() {
		return new Validator();
	}

	/**
	 * Create an instance of {@link Options }
	 * 
	 */
	public Options createOptions() {
		return new Options();
	}

	/**
	 * Create an instance of {@link Category }
	 * 
	 */
	public Category createCategory() {
		return new Category();
	}

	/**
	 * Create an instance of {@link Option }
	 * 
	 */
	public Option createOption() {
		return new Option();
	}

	/**
	 * Create an instance of {@link SimpleConfigItem }
	 * 
	 */
	public SimpleConfigItem createSimpleConfigItem() {
		return new SimpleConfigItem();
	}

	/**
	 * Create an instance of {@link MapConfigItem }
	 * 
	 */
	public MapConfigItem createMapConfigItem() {
		return new MapConfigItem();
	}

	/**
	 * Create an instance of {@link Dependency }
	 * 
	 */
	public Dependency createDependency() {
		return new Dependency();
	}

	/**
	 * Create an instance of {@link OnConfigurationModelChangedListener }
	 * 
	 */
	public OnConfigurationModelChangedListener createOnConfigurationModelChangedListener() {
		return new OnConfigurationModelChangedListener();
	}

	/**
	 * Create an instance of {@link SPARQLConfigItem }
	 * 
	 */
	public SPARQLConfigItem createSPARQLConfigItem() {
		return new SPARQLConfigItem();
	}

	/**
	 * Create an instance of {@link Configuration }
	 * 
	 */
	public Configuration createConfiguration() {
		return new Configuration();
	}

	/**
	 * Create an instance of {@link Item }
	 * 
	 */
	public Item createItem() {
		return new Item();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Configuration
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://universaal.cas.de", name = "configuration")
	public JAXBElement<Configuration> createConfiguration(Configuration value) {
		return new JAXBElement<Configuration>(_Configuration_QNAME, Configuration.class, null, value);
	}

}
