package org.universAAL.tools.ucc.commerce.ustore.tools;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8 2013-06-11T10:49:36.521+02:00
 * Generated source version: 2.6.8
 *
 */
@WebService(targetNamespace = "http://tools.ustore.commerce.universaal.org/", name = "OnlineStoreManager")
@XmlSeeAlso({ ObjectFactory.class })
public interface OnlineStoreManager {

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getUpdatesForServices", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.GetUpdatesForServices")
	@WebMethod
	@ResponseWrapper(localName = "getUpdatesForServicesResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.GetUpdatesForServicesResponse")
	public java.lang.String getUpdatesForServices(
			@WebParam(name = "sessionKey", targetNamespace = "") java.lang.String sessionKey)
			throws UStoreException_Exception;

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getFreeServices", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.GetFreeServices")
	@WebMethod
	@ResponseWrapper(localName = "getFreeServicesResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.GetFreeServicesResponse")
	public java.lang.String getFreeServices(
			@WebParam(name = "sessionKey", targetNamespace = "") java.lang.String sessionKey,
			@WebParam(name = "isFitToUser", targetNamespace = "") boolean isFitToUser) throws UStoreException_Exception;

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getUserProfile", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.GetUserProfile")
	@WebMethod
	@ResponseWrapper(localName = "getUserProfileResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.GetUserProfileResponse")
	public java.lang.String getUserProfile(
			@WebParam(name = "sessionKey", targetNamespace = "") java.lang.String sessionKey)
			throws UStoreException_Exception;

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getPurchasedServices", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.GetPurchasedServices")
	@WebMethod
	@ResponseWrapper(localName = "getPurchasedServicesResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.GetPurchasedServicesResponse")
	public java.lang.String getPurchasedServices(
			@WebParam(name = "sessionKey", targetNamespace = "") java.lang.String sessionKey)
			throws UStoreException_Exception;

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getSessionKey", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.GetSessionKey")
	@WebMethod
	@ResponseWrapper(localName = "getSessionKeyResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.GetSessionKeyResponse")
	public java.lang.String getSessionKey(@WebParam(name = "userName", targetNamespace = "") java.lang.String userName,
			@WebParam(name = "password", targetNamespace = "") java.lang.String password)
			throws UStoreException_Exception;

	@RequestWrapper(localName = "registerDeployManager", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.RegisterDeployManager")
	@WebMethod
	@ResponseWrapper(localName = "registerDeployManagerResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.RegisterDeployManagerResponse")
	public void registerDeployManager(@WebParam(name = "sessionKey", targetNamespace = "") java.lang.String sessionKey,
			@WebParam(name = "adminUserName", targetNamespace = "") java.lang.String adminUserName,
			@WebParam(name = "adminPassword", targetNamespace = "") java.lang.String adminPassword,
			@WebParam(name = "ipAddress", targetNamespace = "") java.lang.String ipAddress,
			@WebParam(name = "port", targetNamespace = "") java.lang.String port) throws UStoreException_Exception;

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "purchaseFreeService", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.PurchaseFreeService")
	@WebMethod
	@ResponseWrapper(localName = "purchaseFreeServiceResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.commerce.ustore.tools.PurchaseFreeServiceResponse")
	public java.lang.String purchaseFreeService(
			@WebParam(name = "sessionKey", targetNamespace = "") java.lang.String sessionKey,
			@WebParam(name = "serviceId", targetNamespace = "") java.lang.String serviceId)
			throws UStoreException_Exception;
}
