
package org.universAAL.tools.ucc.commerce.ustore.tools;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.6.8 2013-06-11T10:49:36.475+02:00
 * Generated source version: 2.6.8
 */

@WebFault(name = "UStoreException", targetNamespace = "http://tools.ustore.commerce.universaal.org/")
public class UStoreException_Exception extends Exception {

	private org.universAAL.tools.ucc.commerce.ustore.tools.UStoreException uStoreException;

	public UStoreException_Exception() {
		super();
	}

	public UStoreException_Exception(String message) {
		super(message);
	}

	public UStoreException_Exception(String message, Throwable cause) {
		super(message, cause);
	}

	public UStoreException_Exception(String message, org.universAAL.tools.ucc.commerce.ustore.tools.UStoreException uStoreException) {
		super(message);
		this.uStoreException = uStoreException;
	}

	public UStoreException_Exception(String message, org.universAAL.tools.ucc.commerce.ustore.tools.UStoreException uStoreException,
			Throwable cause) {
		super(message, cause);
		this.uStoreException = uStoreException;
	}

	public org.universAAL.tools.ucc.commerce.ustore.tools.UStoreException getFaultInfo() {
		return this.uStoreException;
	}
}
