//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.08.02 at 01:53:27 PM MESZ
//

package org.universAAL.tools.ucc.configuration.model.configurationdefinition;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for Category complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Category">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="SPARQLConfigItem" type="{http://universaal.cas.de}SPARQLConfigItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MapConfigItem" type="{http://universaal.cas.de}MapConfigItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SimpleConfigItem" type="{http://universaal.cas.de}SimpleConfigItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Dependencies" type="{http://universaal.cas.de}Dependency" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Category", propOrder = { "sparqlConfigItemAndMapConfigItemAndSimpleConfigItem" })
public class Category {

	@XmlElements({ @XmlElement(name = "Dependencies", type = Dependency.class),
			@XmlElement(name = "SimpleConfigItem", type = SimpleConfigItem.class),
			@XmlElement(name = "MapConfigItem", type = MapConfigItem.class),
			@XmlElement(name = "SPARQLConfigItem", type = SPARQLConfigItem.class) })
	protected List<Object> sparqlConfigItemAndMapConfigItemAndSimpleConfigItem;
	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String id;
	@XmlAttribute(required = true)
	protected String label;
	@XmlAttribute
	protected String description;

	/**
	 * Gets the value of the sparqlConfigItemAndMapConfigItemAndSimpleConfigItem
	 * property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the
	 * sparqlConfigItemAndMapConfigItemAndSimpleConfigItem property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getSPARQLConfigItemAndMapConfigItemAndSimpleConfigItem().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Dependency } {@link SimpleConfigItem } {@link MapConfigItem }
	 * {@link SPARQLConfigItem }
	 *
	 *
	 */
	public List<Object> getSPARQLConfigItemAndMapConfigItemAndSimpleConfigItem() {
		if (sparqlConfigItemAndMapConfigItemAndSimpleConfigItem == null) {
			sparqlConfigItemAndMapConfigItemAndSimpleConfigItem = new ArrayList<Object>();
		}
		return this.sparqlConfigItemAndMapConfigItemAndSimpleConfigItem;
	}

	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the label property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * Sets the value of the label property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLabel(String value) {
		this.label = value;
	}

	/**
	 * Gets the value of the description property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setDescription(String value) {
		this.description = value;
	}

}
