//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.02 at 01:53:27 PM MESZ 
//

package org.universAAL.tools.ucc.configuration.model.configurationdefinition;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for ConfigItem complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dependencies" type="{http://universaal.cas.de}Dependency" minOccurs="0"/>
 *         &lt;element name="validators" type="{http://universaal.cas.de}Validators" minOccurs="0"/>
 *         &lt;element name="onConfigurationModelChangedListener" type="{http://universaal.cas.de}OnConfigurationModelChangedListener" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="active" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="cardinality" default="0..1">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]+..[0-9*]+"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigItem", propOrder = { "label", "description", "dependencies", "validators",
		"onConfigurationModelChangedListener" })
@XmlSeeAlso({ SPARQLConfigItem.class, SimpleConfigItem.class, MapConfigItem.class })
public class ConfigItem {

	@XmlElement(required = true)
	protected String label;
	@XmlElement(required = true)
	protected String description;
	protected Dependency dependencies;
	protected Validators validators;
	protected OnConfigurationModelChangedListener onConfigurationModelChangedListener;
	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String id;
	@XmlAttribute
	protected Boolean active;
	@XmlAttribute
	protected String cardinality;

	/**
	 * Gets the value of the label property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * Sets the value of the label property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLabel(String value) {
		this.label = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the dependencies property.
	 * 
	 * @return possible object is {@link Dependency }
	 * 
	 */
	public Dependency getDependencies() {
		return dependencies;
	}

	/**
	 * Sets the value of the dependencies property.
	 * 
	 * @param value
	 *            allowed object is {@link Dependency }
	 * 
	 */
	public void setDependencies(Dependency value) {
		this.dependencies = value;
	}

	/**
	 * Gets the value of the validators property.
	 * 
	 * @return possible object is {@link Validators }
	 * 
	 */
	public Validators getValidators() {
		return validators;
	}

	/**
	 * Sets the value of the validators property.
	 * 
	 * @param value
	 *            allowed object is {@link Validators }
	 * 
	 */
	public void setValidators(Validators value) {
		this.validators = value;
	}

	/**
	 * Gets the value of the onConfigurationModelChangedListener property.
	 * 
	 * @return possible object is {@link OnConfigurationModelChangedListener }
	 * 
	 */
	public OnConfigurationModelChangedListener getOnConfigurationModelChangedListener() {
		return onConfigurationModelChangedListener;
	}

	/**
	 * Sets the value of the onConfigurationModelChangedListener property.
	 * 
	 * @param value
	 *            allowed object is {@link OnConfigurationModelChangedListener }
	 * 
	 */
	public void setOnConfigurationModelChangedListener(OnConfigurationModelChangedListener value) {
		this.onConfigurationModelChangedListener = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the active property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isActive() {
		if (active == null) {
			return true;
		} else {
			return active;
		}
	}

	/**
	 * Sets the value of the active property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setActive(Boolean value) {
		this.active = value;
	}

	/**
	 * Gets the value of the cardinality property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCardinality() {
		if (cardinality == null) {
			return "0..1";
		} else {
			return cardinality;
		}
	}

	/**
	 * Sets the value of the cardinality property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCardinality(String value) {
		this.cardinality = value;
	}

}
