//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.08.05 at 09:10:43 PM CEST
//

package org.universAAL.tools.ucc.model.usrv;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * describes the hardware part, where the artifactID is the one set by the
 * uStore
 *
 * <p>
 * Java class for hardwareType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="hardwareType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="artifactID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hardwareType", namespace = "http://www.universaal.org/aal-usrv/v1.0.2", propOrder = { "name", "clazz",
		"artifactID", "category" })
public class HardwareType implements Serializable {

	private final static long serialVersionUID = 12343L;
	@XmlElement(required = true)
	protected String name;
	@XmlElement(name = "class", required = true)
	protected String clazz;
	@XmlElement(required = true)
	protected String artifactID;
	@XmlElement(required = true)
	protected String category;

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setName(String value) {
		this.name = value;
	}

	public boolean isSetName() {
		return (this.name != null);
	}

	/**
	 * Gets the value of the clazz property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getClazz() {
		return clazz;
	}

	/**
	 * Sets the value of the clazz property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setClazz(String value) {
		this.clazz = value;
	}

	public boolean isSetClazz() {
		return (this.clazz != null);
	}

	/**
	 * Gets the value of the artifactID property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getArtifactID() {
		return artifactID;
	}

	/**
	 * Sets the value of the artifactID property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setArtifactID(String value) {
		this.artifactID = value;
	}

	public boolean isSetArtifactID() {
		return (this.artifactID != null);
	}

	/**
	 * Gets the value of the category property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * Sets the value of the category property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setCategory(String value) {
		this.category = value;
	}

	public boolean isSetCategory() {
		return (this.category != null);
	}

}
